version: '3.8'
services:
  tr-service:
    container_name: tr-service
    image: ghcr.io/e-permit/service:latest
    pull_policy: always
    depends_on:
      - trdb
    env_file:
      - ../envs/tr.env
    ports:
      - "3050:8080"
    volumes:
      - /var/log/epermit
  uz-service:
    container_name: uz-service
    image: ghcr.io/e-permit/service:latest
    pull_policy: always
    depends_on:
      - uzdb
    env_file:
      - ../envs/uz.env
    ports:
      - "3060:8080"
    volumes:
      - /var/log/epermit
  trdb:
    image: 'postgres:13.1-alpine'
    container_name: trdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
    ports:
      - "5434:5432"
  uzdb:
    image: 'postgres:13.1-alpine'
    container_name: uzdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
    ports:
      - "5433:5432"
