package epermit.commons;

public enum ErrorCodes {
    AUTHORITY_ALREADY_EXISTS,
    AUTHORITY_NOT_FOUND,
    KEYID_ALREADY_EXISTS,
    KEY_NOTFOUND,
    INSUFFICIENT_KEY,
    EVENT_ALREADY_EXISTS,
    PREVIOUS_EVENT_NOTFOUND,
    GENESIS_EVENT_ALREADY_EXISTS,
    INSUFFICIENT_PERMIT_QUOTA,
    INVALID_PERMIT_QUOTA_RANGE,
    PERMITID_ALREADY_EXISTS,
    PERMIT_NOTFOUND,
    PERMIT_USED,
    PERMIT_ALREADY_REVOKED,
    INVALID_PERMITID,
    REMOTE_ERROR;
}
