package epermit.commons;

public enum ErrorCodes {
    EVENT_ALREADY_EXISTS,
    PREVIOUS_EVENT_NOTFOUND,
    INTERNAL_SERVER_ERROR,
    KEYID_ALREADY_EXISTS,
    PERMITID_ALREADY_EXISTS,
    PERMIT_NOTFOUND,
    INVALID_PERMITID,
    PERMIT_ISSUER_EVENT_ISSUER_MISMATCH,
    PERMIT_ISSUEDFOR_EVENT_ISSUEDFOR_MISMATCH;
}
