package epermit.commons;

public enum ErrorCodes {
    AUTHORITY_ALREADY_EXISTS,
    AUTHORITY_NOT_FOUND,
    EVENT_ALREADY_EXISTS,
    PREVIOUS_EVENT_NOTFOUND,
    GENESIS_EVENT_ALREADY_EXISTS,
    INSUFFICIENT_PERMIT_QUOTA,
    PERMITID_ALREADY_EXISTS,
    PERMIT_NOTFOUND,
    PERMIT_USED,
    INVALID_PERMITID,
    REMOTE_ERROR;
}
