version: '3.8'
services:
  a-internal-api:
    container_name: a-internal-api
    build:
      context: ../../e-permit-internal-api
    depends_on:
      - adb
    environment:
      - EPERMIT_ADMIN_PASSWORD=admin
      - EPERMIT_KEYSTORE_PASSWORD=admin
      - FLYWAY_ENABLED=true
      - FLYWAY_SCHEMAS=public
    env_file:
      - a.env
    ports:
      - "3050:8080"
  
  a-public-api:
    container_name: a-public-api
    build:
      context: ../../e-permit-public-api
    depends_on:
      - adb
    env_file:
      - a.env
    ports:
      - "3051:8080"

  adb:
    image: 'postgres:16.2-alpine'
    container_name: adb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
    ports:
      - "5433:5432"
  
  b-internal-api:
    container_name: b-internal-api
    build:
      context: ../../e-permit-internal-api
    depends_on:
      - bdb
    environment:
      - EPERMIT_ADMIN_PASSWORD=admin
      - EPERMIT_KEYSTORE_PASSWORD=admin
      - FLYWAY_ENABLED=true
      - FLYWAY_SCHEMAS=public
    env_file:
      - b.env
    ports:
      - "3060:8080"

  b-public-api:
    container_name: b-public-api
    build:
      context: ../../e-permit-public-api
    depends_on:
      - bdb
    env_file:
      - b.env
    ports:
      - "3061:8080"

  bdb:
    image: 'postgres:16.2-alpine'
    container_name: bdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
    ports:
      - "5434:5432"
