version: '3.7'
services:
  tr-internal-api:
    image: ghcr.io/e-permit/internalapi:latest
    depends_on:
      - trdb
    env_file:
      - tr.env
    ports:
      - "3020:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/tr:/var/log/epermit
  tr-public-api:
    image: ghcr.io/e-permit/publicapi:latest
    depends_on:
      - trdb
    env_file:
      - tr.env
    ports:
      - "3021:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/tr:/var/log/epermit
  uz-internal-api:
    image: ghcr.io/e-permit/internalapi:latest
    depends_on:
      - uzdb
    env_file:
      - uz.env
    ports:
      - "3030:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/uz:/var/log/epermit
  uz-public-api:
    image: ghcr.io/e-permit/publicapi:latest
    depends_on:
      - uzdb
    env_file:
      - uz.env
    ports:
      - "3031:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/tr:/var/log/epermit
  trdb:
    image: 'postgres:13.1-alpine'
    container_name: trdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
  uzdb:
    image: 'postgres:13.1-alpine'
    container_name: uzdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
