version: '3.7'
services:
  tr-internal-api:
    build: 
      context: ../../e-permit-internal-api
    depends_on:
      - trdb
    env_file:
      - tr-shared.env
    ports:
      - "3050:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/tr:/var/log/epermit
  tr-public-api:
    build: 
      context: ../../e-permit-public-api
    depends_on:
      - trdb
    env_file:
      - tr-shared.env
      - tr-public.env
    ports:
      - "3051:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/tr:/var/log/epermit
  uz-internal-api:
    build: 
      context: ../../e-permit-internal-api
    depends_on:
      - uzdb
    env_file:
      - uz-shared.env
    ports:
      - "3060:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/uz:/var/log/epermit
  uz-public-api:
    build: 
      context: ../../e-permit-public-api
    depends_on:
      - uzdb
    env_file:
      - uz-shared.env
      - uz-public.env
    ports:
      - "3061:8080"
    volumes:
      - ${EPERMIT_LOG_VOLUME}/tr:/var/log/epermit
  trdb:
    image: 'postgres:13.1-alpine'
    container_name: trdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
    ports:
      - "5434:5432"
  uzdb:
    image: 'postgres:13.1-alpine'
    container_name: uzdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=devdb
    ports:
      - "5433:5432"
